# LetsGrowMore (LGMVIP) - "DATA SCIENCE INTERNSHIP"

## LGMVIP July-22

### _Author - Zecil Jain_

### Task - 9 Handwritten Equation solver using CNN

This project is aimed at developing a mathematical equation solver using character and symbol recognition by enforcing the image processing techniques and CNN model.

- The dataset is huge and very comprehensive. Since we don't have the adequate provisions in terms of high-end laptop for extracting multitudes of images and analyzing them, we will just make use of a fraction of dataset including the numbers and '+','-' and '*' operators to form a basic equation and test our model in realtime.


- So all in all, the equation can contain any digit from 0-9 and symbol +,x,- Works on image with white background and digits/symbols are in black.


- Future scope of this model can include analyzing all forms of equations by including the complete dataset and including every single operator.

Dataset link: https://www.kaggle.com/xainano/handwrittenmathsymbols 

## Importing Libraries

In [73]:
import numpy as np
import cv2
from PIL import Image
from matplotlib import pyplot as plt
%matplotlib inline
import os
from os import listdir
from os.path import isfile, join
import pandas as pd
import pickle

np.random.seed(1212)
import keras
from keras.utils.np_utils import to_categorical
from keras.models import Model
from keras.datasets import mnist
from keras.layers import *
from keras import optimizers
from keras.layers import Input, Dense
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.utils import np_utils
from keras.models import model_from_json
from keras import backend as K
K.set_image_data_format('channels_last')

Now that we have imported all our libraries, we will move onto the next step which is to load the image sets from our local drive onto the notebook.

## Loading the Dataset

We will be creating a load_images_from_folder function for loading image sets. The reason behind creating a function is because there are a multitude of images in a number of folders in and we have to load all these images from seperate folders onto our notebook. To not repeat typing the same block of code over and over, we will just create a function and run that numerous times till we have loaded all the required images sets.

In [2]:
def load_images_from_folder(folder):
    train_data = [] # empty list for storing the image sets
    for filename in os.listdir(folder):
        # Reading the images one by one using CV2 library
        img = cv2.imread(os.path.join(folder, filename), cv2.IMREAD_GRAYSCALE)
        img =~ img
        if img is not None:
            ret, thresh = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)
            ctrs, hie = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
            cnt = sorted(ctrs, key=lambda ctr: cv2.boundingRect(ctr)[0])
            w = int(28)
            h = int(28)
            max_i = 0
            for c in cnt:
                x,y,w,h = cv2.boundingRect(c)
                max_i = max(w*h,max_i)
                if max_i==(w*h):
                    max_x = x
                    max_y = y
                    max_w = w
                    max_h = h
            img_crop = thresh[max_y : max_y + max_h + 10, max_x : max_x + max_w + 10]
            img_resize = cv2.resize(img_crop, (28,28))
            img_resize = np.reshape(img_resize, (784, 1))
            train_data.append(img_resize)
    return train_data

In [3]:
data = []

Now we will start loading the various image sets from different folders using our function and store them in seperate columns in the above defined empty list.

In [4]:
# Assigning '-' to column 10
data = load_images_from_folder('E:/Data-Science-Projects/LGMVIP--DataScience/Task -9/extracted_images/-')
len(data)
for i in range(0, len(data)):
    data[i] = np.append(data[i], ['10'])
    
print(len(data))

33997


In [5]:
# Assigning '+' to column 11
data11=load_images_from_folder('E:/Data-Science-Projects/LGMVIP--DataScience/Task -9/extracted_images/+')

for i in range(0,len(data11)):
    data11[i]=np.append(data11[i],['11'])
data=np.concatenate((data,data11))
print(len(data))

59109


In [6]:
# Assigning '0' to column 0
data0=load_images_from_folder('E:/Data-Science-Projects/LGMVIP--DataScience/Task -9/extracted_images/0')

for i in range(0,len(data0)):
    data0[i]=np.append(data0[i],['0'])
data=np.concatenate((data,data0))
print(len(data))

66023


In [7]:
# Assigning '1' to column 1
data1=load_images_from_folder('E:/Data-Science-Projects/LGMVIP--DataScience/Task -9/extracted_images/1')

for i in range(0,len(data1)):
    data1[i]=np.append(data1[i],['1'])
data=np.concatenate((data,data1))
print(len(data))

92543


In [8]:
# Assigning '2' to column 2
data2=load_images_from_folder('E:/Data-Science-Projects/LGMVIP--DataScience/Task -9/extracted_images/2')

for i in range(0,len(data2)):
    data2[i]=np.append(data2[i],['2'])
data=np.concatenate((data,data2))
print(len(data))

118684


In [9]:
# Assigning '3' to column 3
data3=load_images_from_folder('E:/Data-Science-Projects/LGMVIP--DataScience/Task -9/extracted_images/3')

for i in range(0,len(data3)):
    data3[i]=np.append(data3[i],['3'])
data=np.concatenate((data,data3))
print(len(data))

129593


In [10]:
# Assigning '4' to column 4
data4=load_images_from_folder('E:/Data-Science-Projects/LGMVIP--DataScience/Task -9/extracted_images/4')

for i in range(0,len(data4)):
    data4[i]=np.append(data4[i],['4'])
data=np.concatenate((data,data4))
print(len(data))

136989


In [11]:
# Assigning '5' to column 5
data5=load_images_from_folder('E:/Data-Science-Projects/LGMVIP--DataScience/Task -9/extracted_images/5')

for i in range(0,len(data5)):
    data5[i]=np.append(data5[i],['5'])
data=np.concatenate((data,data5))
print(len(data))

140534


In [12]:
# Assigning '6' to column 6
data6=load_images_from_folder('E:/Data-Science-Projects/LGMVIP--DataScience/Task -9/extracted_images/6')

for i in range(0,len(data6)):
    data6[i]=np.append(data6[i],['6'])
data=np.concatenate((data,data6))
print(len(data))

143652


In [13]:
# Assigning '7' to column 7
data7=load_images_from_folder('E:/Data-Science-Projects/LGMVIP--DataScience/Task -9/extracted_images/7')

for i in range(0,len(data7)):
    data7[i]=np.append(data7[i],['7'])
data=np.concatenate((data,data7))
print(len(data))

146561


In [14]:
# Assigning '8' to column 8
data8=load_images_from_folder('E:/Data-Science-Projects/LGMVIP--DataScience/Task -9/extracted_images/8')

for i in range(0,len(data8)):
    data8[i]=np.append(data8[i],['8'])
data=np.concatenate((data,data8))
print(len(data))

149629


In [15]:
# Assigning '9' to column 9
data9=load_images_from_folder('E:/Data-Science-Projects/LGMVIP--DataScience/Task -9/extracted_images/9')

for i in range(0,len(data9)):
    data9[i]=np.append(data9[i],['9'])
data=np.concatenate((data,data9))
print(len(data))

153366


In [16]:
# Assigning '* or times' to column 12
data12=load_images_from_folder('E:/Data-Science-Projects/LGMVIP--DataScience/Task -9/extracted_images/times')

for i in range(0,len(data12)):
    data12[i]=np.append(data12[i],['12'])
data=np.concatenate((data,data12))
print(len(data))

156617


## Dataframe creation

We will now create a seperate dataframe using the 'data' list so that we can use that dataframe in the subsequent model building process.

In [17]:
df = pd.DataFrame(data, index=None)
df.to_csv('train_final.csv', index=False)

As we can see, a new dataframe called 'train_final' is created and is filled with all the image sets as records in various columns.

## Creating training set

In [18]:
df_train = pd.read_csv('train_final.csv', index_col = False)
labels = df_train[['784']]

In [19]:
df_train.drop(df_train.columns[[784]], axis=1, inplace=True)
df_train.head()

0    1    2    3    4    5    6    7    8    9  ...  774  775  776  777  \
0  255  255  255  255  255  255  255  255  255  255  ...    0    0    0    0   
1  255  255  255  255  255  255  255  255  255  255  ...    0    0    0    0   
2  255  255  255  255  255  255  255  255  255  255  ...    0    0    0    0   
3  255  255  255  255  255  255  255  255  255  255  ...    0    0    0    0   
4  255  255  255  255  255  255  255  255  255  255  ...    0    0    0    0   

   778  779  780  781  782  783  
0    0    0    0    0    0    0  
1    0    0    0    0    0    0  
2    0    0    0    0    0    0  
3    0    0    0    0    0    0  
4    0    0    0    0    0    0  

[5 rows x 784 columns]

We need the labels of the dataset in a seperate variable which we will use in our category variable creation

In [20]:
labels = np.array(labels)

Using the labels we will create our category variable which will be used while fitting the model to the dataset. This is done so that we can fit our model more accurately.

In [21]:
cat = to_categorical(labels, num_classes=13)

In [22]:
print(cat)

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


Next we will be creating a list with the 'lst' variable and appending all the training set values to it.
We will also reshape the lst in the format of (28, 28, 1) because this is how we will be feeding it to the model.

In [68]:
lst = []
for i in range(156617):
    lst.append(np.array(df_train[i:i+1]).reshape(28,28, 1))

Resetting the seed value to 7 which we had changed in the beginning of our project code block.

In [69]:
np.random.seed(7)

## Model Building

The CNN model will be defined as per our dataset. The layers to be added in the model are:
- __Convolutional Layer__: This layer is the first layer that is used to extract the various features from the input images. We will be using __'_Conv2D_'__ for our convolutional layer requirements


- __Fully Connected Layer__: The Fully Connected (FC) layer consists of the weights and biases along with the neurons and is used to connect the neurons between two different layers. __'_Dense_'__ will be utilized for creating a FC layer here.


- __Dropout__: Usually, when all the features are connected to the FC layer, it can cause overfitting in the training dataset. Overfitting occurs when a particular model works so well on the training data causing a negative impact in the model’s performance when used on a new data. 
    To overcome this problem, a ___dropout layer___ is utilised wherein a few neurons are dropped from the neural network during training process resulting in reduced size of the model. 
    

- __Activation Functions__: Finally, one of the most important parameters of the CNN model is the activation function. They are used to learn and approximate any kind of continuous and complex relationship between variables of the network. In simple words, it decides which information of the model should fire in the forward direction and which ones should not at the end of the network.
    __'_Softmax activation_'__ function will be used which will convert all predictions into probability. Tuning can be performed on the architecture further to get the most optimal performance.

In [70]:
model = Sequential()
model.add(Conv2D(30, (5, 5), input_shape=(28, 28, 1), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(15, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(13, activation='softmax'))

# Compile model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [71]:
model.summary()

Model: "sequential_15"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_24 (Conv2D)          (None, 24, 24, 30)        780       
                                                                 
 max_pooling2d_18 (MaxPoolin  (None, 12, 12, 30)       0         
 g2D)                                                            
                                                                 
 conv2d_25 (Conv2D)          (None, 10, 10, 15)        4065      
                                                                 
 max_pooling2d_19 (MaxPoolin  (None, 5, 5, 15)         0         
 g2D)                                                            
                                                                 
 dropout_9 (Dropout)         (None, 5, 5, 15)          0         
                                                                 
 flatten_9 (Flatten)         (None, 375)             

__Note__: The shape of input required is of (28, 28, 1) type.

## Model Training

We will be making use of the category variable created earlier for the model fitting process.
The input will be lst in the form of array with batch size of 200.

In [72]:
model.fit(np.array(lst), cat, epochs=10, batch_size=200,shuffle=True,verbose=1)

Epoch 1/10
784/784 [==============================] - 122s 148ms/step - loss: 0.4060 - accuracy: 0.8960
Epoch 2/10
784/784 [==============================] - 140s 178ms/step - loss: 0.0961 - accuracy: 0.9720
Epoch 3/10
784/784 [==============================] - 114s 145ms/step - loss: 0.0664 - accuracy: 0.9804
Epoch 4/10
784/784 [==============================] - 101s 129ms/step - loss: 0.0513 - accuracy: 0.9852
Epoch 5/10
784/784 [==============================] - 117s 149ms/step - loss: 0.0419 - accuracy: 0.9874
Epoch 6/10
784/784 [==============================] - 128s 163ms/step - loss: 0.0373 - accuracy: 0.9889
Epoch 7/10
784/784 [==============================] - 130s 166ms/step - loss: 0.0299 - accuracy: 0.9912
Epoch 8/10
784/784 [==============================] - 125s 160ms/step - loss: 0.0296 - accuracy: 0.9911
Epoch 9/10
784/784 [==============================] - 122s 155ms/step - loss: 0.0245 - accuracy: 0.9928
Epoch 10/10
784/784 [==============================] - 136s 174m

Since the model has been trained successfully, lets save this model before we move onto any other evaluation or prediction stages.

In [74]:
model_json = model.to_json()
with open("LGMVIP_Task9_model.json", "w") as json_file:
    json_file.write(model_json)
    
# serialize weights to HDF5
model.save_weights("LGMVIP_Task9_model.h5")

## Making Prediction 

Since our model has been created, we will now move onto the predictions. The initial procedure is almost same as we did while loading our dataset. The steps to be followed here are:

- Input an image containing a handwritten equation. Convert the image to a binary image and then invert the image(if digits/symbols are in black).

- Obtaining the contours of the image by default, it will obtain contours from left to right.

- Obtaining bounding rectangle for each contour.

- Sometimes, we may get two or more contours for the same digit/symbol. To avoid that, we can check if the bounding rectangle of those two contours overlaps or not. If they overlap, then discard the smaller rectangle.

- Now, resize all the remaining bounding rectangle to 28 by 28.

Lastly, we will use our model to predict the corresponding digit/symbol for each bounding rectangle and store it in a string.
After that evaluate the string to produce our results and print it.

In [ ]:
img = cv2.imread('E:/Data-Science-Projects/LGMVIP--DataScience/Task -9/test.jpeg',cv2.IMREAD_GRAYSCALE)
cv2.imshow("wo",img)
cv2.waitKey(0)
cv2.destroyAllWindows()
if img is not None:
    img=~img
    ret,thresh=cv2.threshold(img,127,255,cv2.THRESH_BINARY)
    ctrs,hie=cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
    cnt=sorted(ctrs, key=lambda ctr: cv2.boundingRect(ctr)[0])
    w=int(28)
    h=int(28)
    train_data=[]
    rects=[]
    for c in cnt :
        x,y,w,h= cv2.boundingRect(c)
        rect=[x,y,w,h]
        rects.append(rect)
    bool_rect=[]
    for r in rects:
        l=[]
        for rec in rects:
            flag=0
            if rec!=r:
                if r[0]<(rec[0]+rec[2]+10) and rec[0]<(r[0]+r[2]+10) and r[1]<(rec[1]+rec[3]+10) and rec[1]<(r[1]+r[3]+10):
                    flag=1
                l.append(flag)
            if rec==r:
                l.append(0)
        bool_rect.append(l)
    dump_rect=[]
    for i in range(0,len(cnt)):
        for j in range(0,len(cnt)):
            if bool_rect[i][j]==1:
                area1=rects[i][2]*rects[i][3]
                area2=rects[j][2]*rects[j][3]
                if(area1==min(area1,area2)):
                    dump_rect.append(rects[i])
    final_rect=[i for i in rects if i not in dump_rect]
    for r in final_rect:
        x=r[0]
        y=r[1]
        w=r[2]
        h=r[3]
        im_crop =thresh[y:y+h+10,x:x+w+10]
        

        im_resize = cv2.resize(im_crop,(28,28))
        cv2.imshow("work",im_resize)
        cv2.waitKey(0)
        cv2.destroyAllWindows()

        im_resize=np.reshape(im_resize,(1,28,28))
        train_data.append(im_resize)

The processing of the test input image has been completed and we have our final 'train_data' ready for evaluation. Here we will use our model to analyze the input data and make prediction accordingly to check the accuracy of our model on unseen data.

In [ ]:
s=''
for i in range(len(train_data)):
    train_data[i]=np.array(train_data[i])
    train_data[i]=train_data[i].reshape(1,1,28,28)
    result=model.predict_classes(train_data[i])
    if(result[0]==10):
        s=s+'-'
    if(result[0]==11):
        s=s+'+'
    if(result[0]==12):
        s=s+'*'
    if(result[0]==0):
        s=s+'0'
    if(result[0]==1):
        s=s+'1'
    if(result[0]==2):
        s=s+'2'
    if(result[0]==3):
        s=s+'3'
    if(result[0]==4):
        s=s+'4'
    if(result[0]==5):
        s=s+'5'
    if(result[0]==6):
        s=s+'6'
    if(result[0]==7):
        s=s+'7'
    if(result[0]==8):
        s=s+'8'
    if(result[0]==9):
        s=s+'9'
    
print(s) 

The project has been completed successfully and the model has been trained to be reliable and efficient enough the make predictions in realtime scenarios on unseen datasets.

__Note__: The model requires Tensorflow to work with CUDA which is only supported by NVIDIA GPUs. Since the system on which this project was developed had AMD powered GPU, making predictions was not a possibility but the model is reliable enough to be tested elsewhere in systems having all necessary requirements to support the process.